name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no need to build locally)
        uses: actions/checkout@v4

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/klapideas-site
            git fetch origin
            git reset --hard origin/main
            docker compose up -d --build --remove-orphans
            docker compose ps
